import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import NavbarMain from "@/components/navbar/navbar-main";
import Footer from "@/components/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs" className="scroll-p-44 scroll-smooth focus:scroll-auto">
      <body className={poppins.className}>
        <NavbarMain />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
