import type { Metadata } from "next";
import { ServiceHero } from "@/components/services/service-hero";
import jsonData from "@/data/services.json"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ServiceHero services={jsonData} />
      {children}
    </>
  );
}
